name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt update
        rustup component add rust-src
        cargo install cargo-binutils
        rustup component add llvm-tools-preview
    - name: Build
      run: |
        ./build.sh
    - name: Run tests
      run: cargo test --verbose
